Update message format

diff --git a/bin/mk b/bin/mk
--- a/bin/mk
+++ b/bin/mk
@@ -11,10 +11,10 @@ do
     cd ..
     if test "$_prev" == "`pwd`"
     then
-        echo "$makefile not found in any parent directories" 1>&2
+        echo "[`basename "$0"`] $makefile not found in any parent directories" 1>&2
         exit 1
     fi
 done
-echo "[$0] Change directory to `pwd`" 1>&2
+echo "[`basename "$0"`] Change directory to `pwd`" 1>&2
 
 make "$@"
